services:
  minecraft-server:
    image: communities:latest
    build: .
    ports:
      - 25565:25565
      - 25575:25575
      - 3876:3876
      - 24454:24454
    volumes:
      - type: bind
        source: ./data-dir
        target: /communities

    ## limits for using `docker compose up`
    mem_limit: 12G
    mem_reservation: 8G
    cpus: '2.0'
    # one big core (4,16), one little core (11,12)
    cpuset: '1,2'

    # specific to deployments
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 9G
        reservations:
          cpus: '2.0'
          memory: 6G
